### ISSUE TITLE
Room segmentation

### ISSUE THREAD

**Issue by tonhathuy** [PRBonn/SIMP#2]
Hi,
I see in the config you need a segment image of the static map. How can I create that image? 
Thanks

**Comment by FullMetalNicky** [comment]
You can either annotate it by hand, e.g. using GIMP, or you can try to use our previous work [Maphisto](https://github.com/FullMetalNicky/Maphisto). If the floor plan is just rectangular rooms, and is axis-aligned, segmentation can be extracted automatically. You should be able to get some hints from CreateMapAssests.py.

**Comment by tonhathuy** [comment]
Thank you for your reply.

**Comment by hzh3gg** [comment]
> Thank you for your reply.

Sorry to bother you, have you successfully run the project online?
