### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by W-ZWei** [PRBonn/SIMP#5]
Hi,Thanks for your contribution, I have a small request:
Your training model download URL：https://www.ipb.uni-bonn.de/html/projects/simp/model_recent.pth. I can't open it, can you provide me with another model file? You can send it to my email (202017456@mail.sdu.edu.cn)，if it is convenient to you. I will be very grateful.
 Thank you!

**Comment by FullMetalNicky** [comment]
@matteosodano Can you check why it's not on the ipb server?

**Comment by matteosodano** [comment]
Model is temporarily here: https://drive.google.com/file/d/1v6QLDOXPurDnpHGFgMwxe1Jyfzzspr4v/view?usp=sharing

We're currently experiencing some issues with the website, and that's the reason why the link is unreachable. The website will be up and running again in the next days and the link in the README will be valid again (I'll remove the model from google drive then).

**Comment by hzh3gg** [comment]
@wangzhiwei-sunyanli  Sorry to bother you, have you successfully run the project online?
