### ISSUE TITLE
Map.yaml

### ISSUE THREAD

**Issue by W-ZWei** [PRBonn/SIMP#6]
I am very interested in your research and grateful for your open source code, but I have a question that I would like to ask the author. How are Map.png and Map_Empty.png generated under the files ncore/data/floor/GTMap/0 or ncore/data/floor/ICPMap/0 or ncore/data/floor/KPMap/0.

**Comment by FullMetalNicky** [comment]
The map format is the same as map_server standard of ROS. 0 is occupied, 255 is free, 205 is unknown in the occupancy grid. Then the .yaml has some additional meta, like the resolution of the map, the 3D origin coordinates, etc. 
You can either acquire such map from a ROS slam package like gmapping or extract it yourself from a floor plan (which is what we did, as the name of our paper suggests).
